apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12
          ports:
            - containerPort: 5672
          resources:
            limits:
              cpu: 100m
