apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azure-devops-app
  template:
    metadata:
      labels:
        app: azure-devops-app
    spec:
      containers:
      - name: azure-devops-api-container
        image: docker.io/francomoreno/azure-devops-api-v2:2.0
        resources:
          requests:
            cpu: "200m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 900
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 900
          periodSeconds: 5
        ports:
          - containerPort: 8000 
